version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: coffeelink_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffeelink
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffeelink_net

volumes:
  postgres_data:

networks:
  coffeelink_net:
